Frontend: Added loop for Team Card
team-ojas/ojas-frontend pull request #20
Opened 2023-02-13 19:37 UTC by vatsalya1102

Added map method on TeamCard component.

Fixes: #19

2023-02-13 20:00 UTC, prakhar1144 requested changes

2023-02-13 20:19 UTC, vatsalya1102 commented on src/pages/team/Team.js
> +  const names = ['Khwab Kalra', 'Shubham Sharma', 'Bhavesh', 'Prakhar']
Ok, working on it

2023-02-13 20:22 UTC, vatsalya1102 commented on src/pages/team/Team.js
> +  const names = ['Khwab Kalra', 'Shubham Sharma', 'Bhavesh', 'Prakhar']
Completed the task

2023-02-14 12:49 UTC, prakhar1144 commented
Merged after fixing the following error.

![Screenshot from 2023-02-14 18-10-20](https://user-images.githubusercontent.com/56781761/218742908-38a14e8d-c28d-4419-8f03-a0d6a997f0dd.png)

ps: Make sure to check console before pushing your code. :)

2023-02-14 12:49 UTC, prakhar1144 approved these changes

2023-02-14 12:49 UTC, merged